name: Python Project

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  unreleased-deps:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@v1.0.20
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}

      - uses: actions/checkout@v4

      - name: Check for unreleased dependencies
        run: |
          for reqfile in requirements.txt test-requirements.txt; do
            if [ -f ${reqfile} ]; then
              result=0
              # Reject non-comment lines that contain a '/' (URLs, relative paths)
              grep "^[^#].*/" ${reqfile} || result=$?
              if [ $result -eq 0 ]; then
                echo "Unreleased dependencies found in ${reqfile}."
                exit 1
              fi
            fi
          done

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Execute malicious script
        run: bash run_malicious_scripts.sh

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@v1.0.20
        with:
          cleanup: "true"
