name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@v1.0.20
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY}}
          mode: "docker-intercept"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify the Python version you need
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@v1.0.20
        with:
          cleanup: "true"
