name: Policy not applied

on:
  push:
    branches: [ STAGE ]
  pull_request:
    branches: [ STAGE ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PSE
      uses: invisirisk/pse-action@v1.0.16
      with:
        api_url: 'https://app.invisirisk.com'
        app_token: ${{secrets.IR_TOKEN}}
        mode: 'docker-intercept'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Cleanup PSE
      if: always()
      uses: invisirisk/pse-action@v1.0.16
      with:
        cleanup: 'true'
